### ISSUE TITLE
Dragging fit induces incorrect bitmap

### ISSUE THREAD

**Issue by blitzmann** [DarkFenX/Pyfa#303]
Dragging a fit to boost or project causes: (fixed)

	Traceback (most recent call last):
	  File "C:\Users\Ryan\Dropbox\Git\blitzmann\Pyfa\gui\sfBrowserItem.py", line 328, in OnLeftDown
		self.CaptureMouse()
	  File "C:\Users\Ryan\Dropbox\WinPython-32bit-2.7.6.2\python-2.7.6\lib\site-packages\wx-3.0-msw\wx\_core.py", line 10641, in CaptureMouse
		return _core_.Window_CaptureMouse(*args, **kwargs)
	wx._core.PyAssertionError: C++ assertion "!wxMouseCapture::IsInCaptureStack(this)" failed at ..\..\src\common\wincmn.cpp(3271) in wxWindowBase::CaptureMouse(): Recapturing the mouse in the same window?

New issue:
Incorrect bitmap when dragged on wx3

**Comment by blitzmann** [comment]
Commenting the CaptureMouse() line here seems to fix this:

https://github.com/DarkFenX/Pyfa/blob/wx3/gui/sfBrowserItem.py#L328

It technically works for 2.8 as well, however there seems to be a bit of a delay when clicking it to when it sets it to drag. Maybe just have to call this depending on version.

Also, the dragging bitmap is totally bonkers on wx3, will have to take a look at that as well

**Comment by blitzmann** [comment]
b54e3aeaf9a1cd6cb21262f7a91b98b88e93aeb0 fixes the issue of the error, and also fixes the delay I was experiencing. I've changed the title to reflect the new issue of a seemingly black bitmap upon drag:

![untitled](https://cloud.githubusercontent.com/assets/3904767/8192502/a08800a4-143c-11e5-8ad2-86eef809f9c6.png)

**Comment by blitzmann** [comment]
I remember the Chrome tabs having black rendering issues in wx3, and I fixed that simply by initializing wx.EmptyBitmap with a depth of 24. The drag bitmap was made with an EmptyBitmap, and so applying the same fix seems to do the same trick here.

There are multiple other occurrences of EmptyBitmap that I'll look into and see if they have a negative effect in wx3
