### ISSUE TITLE
Pyfa will not launch

### ISSUE THREAD

**Issue by BraxtonDallocort** [DarkFenX/Pyfa#320]
I just downloaded pyfa for the first time and everytime i try to launch it it fails to do so. At first i was receiving permission errors so i ran as admin, but now it wont launch and is refering me to a file for more details. I found the file that it was referring to and this is all i found. 

Traceback (most recent call last):
  File "pyfa.py", line 70, in <module>
    usage = "usage: %prog [--root]"
  File "C:\Users\Braxton\Downloads\pyfa-1.13.0-aegis-1.0-win\pyfa\.\config.py", line 62, in defPaths
    handler = logging.handlers.RotatingFileHandler(os.path.join(savePath, "log.txt"), maxBytes=1000000, backupCount=3)
  File "logging\handlers.pyo", line 113, in __init__
    
  File "logging\handlers.pyo", line 65, in __init__
    
  File "logging\__init__.pyo", line 889, in __init__
    
  File "logging\__init__.pyo", line 908, in _open
    
IOError: [Errno 2] No such file or directory: u'C:\\Users\\Braxton\\.pyfa\\log.txt'
Traceback (most recent call last):
  File "pyfa.py", line 70, in <module>
    usage = "usage: %prog [--root]"
  File "C:\Users\Braxton\Downloads\pyfa-1.13.0-aegis-1.0-win\pyfa\.\config.py", line 62, in defPaths
    handler = logging.handlers.RotatingFileHandler(os.path.join(savePath, "log.txt"), maxBytes=1000000, backupCount=3)
  File "logging\handlers.pyo", line 113, in __init__
    
  File "logging\handlers.pyo", line 65, in __init__
    
  File "logging\__init__.pyo", line 889, in __init__
    
  File "logging\__init__.pyo", line 908, in _open
    
IOError: [Errno 2] No such file or directory: u'C:\\Users\\Braxton\\.pyfa\\log.txt'

Id appreciate help on what to do next.

**Comment by blitzmann** [comment]
This was fixed this morning. I am uploading new release files. Check back in about 15 minutes =D
