### ISSUE TITLE
No new Fitting or view old one possible

### ISSUE THREAD

**Issue by Niepel** [DarkFenX/Pyfa#372]
Hello,

since Pyfa Galatea 1.14.0 i cant make new fiitings or view old fittings.
A new installation with the .exe file, a manuel installation of both version have the same problem.
    
    Pyfa.exe.log
    2015-10-01 01:14:17,397 STDERR ERROR Traceback (most recent call last):
    2015-10-01 01:14:17,397 STDERR ERROR File "F:\Pyfa\pyfa\.\gui\sfBrowserItem.py", line 318, in OnLeftUp
    2015-10-01 01:14:17,421 STDERR ERROR btn.DoCallback()
    2015-10-01 01:14:17,421 STDERR ERROR File "F:\Pyfa\pyfa\.\gui\sfBrowserItem.py", line 49, in DoCallback
    2015-10-01 01:14:17,421 STDERR ERROR self.callback()
    2015-10-01 01:14:17,421 STDERR ERROR File "F:\Pyfa\pyfa\.\gui\shipBrowser.py", line 1654, in deleteBtnCB
    2015-10-01 01:14:17,473 STDERR ERROR self.deleteFit()
    2015-10-01 01:14:17,474 STDERR ERROR File "F:\Pyfa\pyfa\.\gui\shipBrowser.py", line 1663, in deleteFit
    2015-10-01 01:14:17,484 STDERR ERROR fit = sFit.getFit(self.fitID)
    2015-10-01 01:14:17,484 STDERR ERROR File "F:\Pyfa\pyfa\.\service\fit.py", line 247, in getFit
    2015-10-01 01:14:17,486 STDERR ERROR for fitP in fit.projectedFits:
    2015-10-01 01:14:17,487 STDERR ERROR File "F:\Pyfa\pyfa\.\eos\saveddata\fit.py", line 212, in projectedFits
    2015-10-01 01:14:17,490 STDERR ERROR return [fit for fit in self.__projectedFits.values() if not fit.isInvalid]
    2015-10-01 01:14:17,490 STDERR ERROR File "sqlalchemy\ext\associationproxy.pyo", line 237, in __get__
    2015-10-01 01:14:17,496 STDERR ERROR File "sqlalchemy\ext\associationproxy.pyo", line 281, in _new
    2015-10-01 01:14:17,502 STDERR ERROR File "sqlalchemy\ext\associationproxy.pyo", line 411, in __call__
    2015-10-01 01:14:17,506 STDERR ERROR File "sqlalchemy\orm\attributes.pyo", line 168, in __get__
    2015-10-01 01:14:17,509 STDERR ERROR c
    2015-10-01 01:14:17,509 STDERR ERROR File "sqlalchemy\orm\attributes.pyo", line 424, in get
    2015-10-01 01:14:17,510 STDERR ERROR File "sqlalchemy\orm\strategies.pyo", line 563, in _load_for_state
    2015-10-01 01:14:17,513 STDERR ERROR File "sqlalchemy\orm\query.pyo", line 1922, in all
    2015-10-01 01:14:17,520 STDERR ERROR File "sqlalchemy\orm\query.pyo", line 2032, in __iter__
    2015-10-01 01:14:17,526 STDERR ERROR File "sqlalchemy\orm\query.pyo", line 2047, in _execute_and_instances
    2015-10-01 01:14:17,532 STDERR ERROR File "sqlalchemy\engine\base.pyo", line 1399, in execute
    2015-10-01 01:14:17,536 STDERR ERROR File "sqlalchemy\engine\base.pyo", line 1532, in _execute_clauseelement
    2015-10-01 01:14:17,540 STDERR ERROR File "sqlalchemy\engine\base.pyo", line 1640, in _execute_context
    2015-10-01 01:14:17,543 STDERR ERROR File "sqlalchemy\engine\base.pyo", line 1633, in _execute_context
    2015-10-01 01:14:17,548 STDERR ERROR File "sqlalchemy\engine\default.pyo", line 330, in do_execute
    2015-10-01 01:14:17,549 STDERR ERROR sqlalchemy.exc
    2015-10-01 01:14:17,549 STDERR ERROR .
    2015-10-01 01:14:17,549 STDERR ERROR OperationalError
    2015-10-01 01:14:17,549 STDERR ERROR :
    2015-10-01 01:14:17,549 STDERR ERROR (OperationalError) no such column: projectedFits.active u'SELECT "projectedFits".amount AS "projectedFits_amount", "projectedFits"."sourceID" AS "projectedFits_sourceID", "projectedFits"."victimID" AS "projectedFits_victimID", "projectedFits".active AS "projectedFits_active" \nFROM "projectedFits" \nWHERE ? = "projectedFits"."victimID"' (5,)

This is my savaddata.db. i was told to uplade it here to.
http://www.daten-hoster.de/file/details/512694/saveddata.rar

MfG
Kay

**Comment by droppedoncaprica** [comment]
Here's a working download link, so people won't have to input their email address.

http://www.daten-hoster.de/file/details/512694/xRdEdfjNdeNORCPH/saveddata.rar

**Comment by blitzmann** [comment]
Hey thanks for reporting here. I haven't looked at the database yet, but this sounds like a failed data migration for some reason. The database column that can't be found should have been added with 1.14 I believe. Which version did you have before this? 

Also, do you see any databases that start with `saveddata_migration`? If so, upload them as well for more diagnostics.

**Comment by blitzmann** [comment]
So, the file you uploaded contains the wrong files. Your `saveddata.db` is a single file that is found in the `.pyfa` directory in your user directory. So, if you're on Windows, that would be `C:/Users/<name>/.pyfa/saveddata.db`

Again, if you see any migration database in there, upload those as well.

**Comment by Niepel** [comment]
Oh, sorry my bad. I didnt know the folder C:/Users/<name>/.pyfa, but I think i found the problem. I installed the new version without deleting the folder under c:/. Now after deleting the it everything works fine. I just updated like always by deleting the old files and extrac the new one, this works fine with all versions till 1.13.2. 

Im very sorry for this stupid mistake.

**Comment by blitzmann** [comment]
Seems to have been a very odd problem though. Even if you had an older version, running the new version should have updated your database. Still not sure how that happened.

Oh well, glad you got it sorted out. =)
