### ISSUE TITLE
CFNetwork error prevents startup - OSX 10.9

### ISSUE THREAD

**Issue by jordillo** [DarkFenX/Pyfa#395]
v1.16.2 - on my Macbook Pro running OSX 10.9.5

popup says "pyfa Error", let's me choose between Terminate and Open Console

Console output:
```
03.11.15 18:49:34,948 apsd[195]: Unrecognized leaf certificate
03.11.15 18:50:20,334 pyfa[952]: Traceback (most recent call last):
03.11.15 18:50:20,334 pyfa[952]:   File "/Applications/Spiele/pyfa.app/Contents/Resources/__boot__.py", line 355, in <module>
03.11.15 18:50:20,335 pyfa[952]:     _run()
03.11.15 18:50:20,335 pyfa[952]:   File "/Applications/Spiele/pyfa.app/Contents/Resources/__boot__.py", line 336, in _run
03.11.15 18:50:20,335 pyfa[952]:     exec(compile(source, path, 'exec'), globals(), globals())
03.11.15 18:50:20,335 pyfa[952]:   File "/Applications/Spiele/pyfa.app/Contents/Resources/pyfa.py", line 99, in <module>
03.11.15 18:50:20,336 pyfa[952]:     import wx
03.11.15 18:50:20,336 pyfa[952]:   File "wx/__init__.pyc", line 45, in <module>
03.11.15 18:50:20,336 pyfa[952]:   File "wx/_core.pyc", line 4, in <module>
03.11.15 18:50:20,336 pyfa[952]:   File "wx/_core_.pyc", line 14, in <module>
03.11.15 18:50:20,336 pyfa[952]:   File "wx/_core_.pyc", line 10, in __load
03.11.15 18:50:20,336 pyfa[952]: ImportError: dlopen(/Applications/Spiele/pyfa.app/Contents/Resources/lib/python2.7/lib-dynload/wx/_core_.so, 2): Symbol not found: _OBJC_CLASS_$_NSURLRequest
03.11.15 18:50:20,337 pyfa[952]:   Referenced from: /Applications/Spiele/pyfa.app/Contents/MacOS/../Frameworks/libwx_osx_cocoau_core-3.0.0.2.0.dylib
03.11.15 18:50:20,337 pyfa[952]:   Expected in: /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
03.11.15 18:50:20,337 pyfa[952]:  in /Applications/Spiele/pyfa.app/Contents/MacOS/../Frameworks/libwx_osx_cocoau_core-3.0.0.2.0.dylib
03.11.15 18:50:20,410 pyfa[952]: pyfa Error
03.11.15 18:50:20,410 pyfa[952]: 2015-11-03 18:50:20.408 pyfa[952:707] pyfa Error
03.11.15 18:51:16,890 com.apple.launchd.peruser.501[166]: (org.evefit.pya.96832[952]) Exited with code: 255
03.11.15 18:51:17,031 Console[958]: setPresentationOptions called with NSApplicationPresentationFullScreen when there is no visible fullscreen window; this call will be ignored.
```

let me know if you need any add'l info

**Comment by blitzmann** [comment]
I have no idea what this means. I'll try to look into it as soon as possible

**Comment by blitzmann** [comment]
I had someone eve-mail me this, seems to be the same issue:

```
I tried the new PYFA. it would not run, the error being nothing more than "PYFA error". The console had this:

11/16/15 1:03:09.983 PM pyfa[42956]: Traceback (most recent call last):
11/16/15 1:03:09.983 PM pyfa[42956]:   File "/Users/hibbs/Documents/EVE/pyfa.app/Contents/Resources/__boot__.py", line 355, in
11/16/15 1:03:09.983 PM pyfa[42956]:     _run()
11/16/15 1:03:09.983 PM pyfa[42956]:   File "/Users/hibbs/Documents/EVE/pyfa.app/Contents/Resources/__boot__.py", line 336, in _run
11/16/15 1:03:09.983 PM pyfa[42956]:     exec(compile(source, path, 'exec'), globals(), globals())
11/16/15 1:03:09.983 PM pyfa[42956]:   File "/Users/hibbs/Documents/EVE/pyfa.app/Contents/Resources/pyfa.py", line 99, in
11/16/15 1:03:09.983 PM pyfa[42956]:     import wx
11/16/15 1:03:09.984 PM pyfa[42956]:   File "wx/__init__.pyc", line 45, in
11/16/15 1:03:09.984 PM pyfa[42956]:   File "wx/_core.pyc", line 4, in
11/16/15 1:03:09.984 PM pyfa[42956]:   File "wx/_core_.pyc", line 14, in
11/16/15 1:03:09.984 PM pyfa[42956]:   File "wx/_core_.pyc", line 10, in __load
11/16/15 1:03:09.984 PM pyfa[42956]: ImportError: dlopen(/Users/hibbs/Documents/EVE/pyfa.app/Contents/Resources/lib/python2.7/lib-dynload/wx/_core_.so, 2): Symbol not found: _OBJC_CLASS_$_NSURLRequest
11/16/15 1:03:09.984 PM pyfa[42956]:   Referenced from: /Users/hibbs/Documents/EVE/pyfa.app/Contents/MacOS/../Frameworks/libwx_osx_cocoau_core-3.0.0.2.0.dylib
11/16/15 1:03:09.984 PM pyfa[42956]:   Expected in: /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
11/16/15 1:03:09.985 PM pyfa[42956]:  in /Users/hibbs/Documents/EVE/pyfa.app/Contents/MacOS/../Frameworks/libwx_osx_cocoau_core-3.0.0.2.0.dylib
11/16/15 1:03:10.050 PM pyfa[42956]: pyfa Error
11/16/15 1:03:10.050 PM pyfa[42956]: 2015-11-16 13:03:10.049 pyfa[42956:707] pyfa Error

Hope it helps find the issue. Thanks!
```

**Comment by jordillo** [comment]
wish i could help you out here but i'm not savvy. can't do much more than
point at something that's broken, then let the smart people fix it.  ;-)

thanks for taking the trouble and making pyfa though - best thing since
sliced bread!

2015-11-17 0:29 GMT+01:00 blitzmann <notifications@github.com>:

**Comment by blitzmann** [comment]
This may be a 10.9.5 problem, as you and the other guy both have that version.

**Comment by simonszu** [comment]
Whew. According to Apple's developer reference, the NSURLRequest class should be available since 10.2. 
Can you check if `/System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork` is a valid path on your system? If not, what is the deepest directory in this path which still exists?

**Comment by jordillo** [comment]
looks like it's all there, with CFNetwork being an executable

kind regards,

jordi

2015-11-18 21:34 GMT+01:00 Simon Szustkowski <notifications@github.com>:

**Comment by sftcpom** [comment]
I'm also getting the same error on the 1.16.2 wx3 build, log attached below.

I'm also running 10.9.5, and the aforementioned CFNetwork path does exist.

Cheers!

```
19/11/2015 15:00:28.312 pyfa[29309]: Traceback (most recent call last):
19/11/2015 15:00:28.312 pyfa[29309]:   File "/Applications/pyfa.app/Contents/Resources/__boot__.py", line 355, in <module>
19/11/2015 15:00:28.312 pyfa[29309]:     _run()
19/11/2015 15:00:28.312 pyfa[29309]:   File "/Applications/pyfa.app/Contents/Resources/__boot__.py", line 336, in _run
19/11/2015 15:00:28.312 pyfa[29309]:     exec(compile(source, path, 'exec'), globals(), globals())
19/11/2015 15:00:28.313 pyfa[29309]:   File "/Applications/pyfa.app/Contents/Resources/pyfa.py", line 99, in <module>
19/11/2015 15:00:28.313 pyfa[29309]:     import wx
19/11/2015 15:00:28.313 pyfa[29309]:   File "wx/__init__.pyc", line 45, in <module>
19/11/2015 15:00:28.313 pyfa[29309]:   File "wx/_core.pyc", line 4, in <module>
19/11/2015 15:00:28.313 pyfa[29309]:   File "wx/_core_.pyc", line 14, in <module>
19/11/2015 15:00:28.313 pyfa[29309]:   File "wx/_core_.pyc", line 10, in __load
19/11/2015 15:00:28.313 pyfa[29309]: ImportError: dlopen(/Applications/pyfa.app/Contents/Resources/lib/python2.7/lib-dynload/wx/_core_.so, 2): Symbol not found: _OBJC_CLASS_$_NSURLRequest
19/11/2015 15:00:28.314 pyfa[29309]:   Referenced from: /Applications/pyfa.app/Contents/MacOS/../Frameworks/libwx_osx_cocoau_core-3.0.0.2.0.dylib
19/11/2015 15:00:28.314 pyfa[29309]:   Expected in: /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
19/11/2015 15:00:28.314 pyfa[29309]:  in /Applications/pyfa.app/Contents/MacOS/../Frameworks/libwx_osx_cocoau_core-3.0.0.2.0.dylib
19/11/2015 15:00:28.380 pyfa[29309]: pyfa Error
19/11/2015 15:00:28.381 pyfa[29309]: 2015-11-19 15:00:28.379 pyfa[29309:707] pyfa Error
```

**Comment by blitzmann** [comment]
Hi guys,

please check here and report https://github.com/DarkFenX/Pyfa/issues/289#issuecomment-158735494

**Comment by blitzmann** [comment]
Closing this now as the new osx binaries fix this issue from what I can tell. If after the next release this issue persists, please reopen
