### ISSUE TITLE
Ubuntu 14.04 Pyfa not start

### ISSUE THREAD

**Issue by 451F** [DarkFenX/Pyfa#415]
``` 
./pyfa.py -w
Traceback (most recent call last):
  File "./pyfa.py", line 104, in <module>
    import service.prefetch
  File "/home/max/Apps/pyfa/service/__init__.py", line 16, in <module>
    from service.pycrest import EVE
  File "/home/max/Apps/pyfa/service/pycrest/__init__.py", line 13, in <module>
    from .eve import EVE
  File "/home/max/Apps/pyfa/service/pycrest/eve.py", line 11, in <module>
    from weak_ciphers import WeakCiphersAdapter
  File "/home/max/Apps/pyfa/service/pycrest/weak_ciphers.py", line 20, in <module>
    from urllib3.util import ssl_
ImportError: cannot import name ssl_
```

**Comment by blitzmann** [comment]
Duplicate #407, already fixed in repo
