### ISSUE TITLE
Tooltip error when clicking state column of blank module

### ISSUE THREAD

**Issue by blitzmann** [DarkFenX/Pyfa#451]
```
Traceback (most recent call last):
  File "C:\Users\Ryan\Copy\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 529, in click
    self.SetToolTipString(tooltip)
  File "C:\Users\Ryan\Copy\WinPython-32bit-2.7.10.1\python-2.7.10\lib\site-packages\wx-3.0-msw\wx\_core.py", line 11386, in SetToolTipString
    return _core_.Window_SetToolTipString(*args, **kwargs)
TypeError: String or Unicode type required
```

**Comment by blitzmann** [comment]
This was fixed in sisi branch accidently, will be merged into master with release
