### ISSUE TITLE
Remote Sensor Dampeners don't load

### ISSUE THREAD

**Issue by thorr18** [DarkFenX/Pyfa#469]
Bad attribute in Remote Sensor Dampeners 1.17.0
~~~
Dec  9 04:13:40  pyfa[884] <Notice>: Traceback (most recent call last):
Dec  9 04:13:40  pyfa[884] <Notice>:   File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa1170.app/Contents/Resources/lib/python2.7/site-packages.zip/gui/marketBrowser.py", line 287, in selectionMade
Dec  9 04:13:40  pyfa[884] <Notice>:   File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa1170.app/Contents/Resources/lib/python2.7/site-packages.zip/service/market.py", line 557, in getItemsByMarketGroup
Dec  9 04:13:40  pyfa[884] <Notice>:   File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa1170.app/Contents/Resources/lib/python2.7/site-packages.zip/service/market.py", line 508, in getVariationsByItems
Dec  9 04:13:40  pyfa[884] <Notice>:   File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa1170.app/Contents/Resources/lib/python2.7/site-packages.zip/service/market.py", line 354, in getItem
Dec  9 04:13:40  pyfa[884] <Notice>:   File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa1170.app/Contents/Resources/lib/python2.7/site-packages.zip/eos/db/gamedata/queries.py", line 56, in checkAndReturn
Dec  9 04:13:40  pyfa[884] <Notice>:   File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa1170.app/Contents/Resources/lib/python2.7/site-packages.zip/eos/db/gamedata/queries.py", line 86, in getItem
Dec  9 04:13:40  pyfa[884] <Notice>: AttributeError: 'NoneType' object has no attribute 'ID'
~~~

**Comment by blitzmann** [comment]
Fixed 0dd98330aaea40b19b5c1c05be1578

Thanks
