### ISSUE TITLE
Copy pasting Fittings doesn't work

### ISSUE THREAD

**Issue by SpeedProg** [DarkFenX/Pyfa#474]
with the current version 1.17.1 I can't copy&past fittings into it

**Comment by SpeedProg** [comment]
okay, nvm I thought it was a problem with the version since it didn't work after reinstalling 1.17.1 but it worked after going back to 1.17.0
But now I went back to 1.17.1 from 1.17.0 and it works again.
No idea what happened but I am gonna close this.

**Comment by blitzmann** [comment]
Just for reference, which OS are you using? But glad it's working again =)

**Comment by SpeedProg** [comment]
was windows 10, installed with the *-win.exe version in a none C:\Program Files* dir.

**Comment by blitzmann** [comment]
I'm going to reopen this as a friend has talk be that he is having problems as well, specifically with this fit:

```
[Cormorant, Cormorant]
Tracking Enhancer II
Magnetic Field Stabilizer II

Tracking Computer II
Sensor Booster II
5MN Y-T8 Compact Microwarpdrive

150mm Railgun II
150mm Railgun II
150mm Railgun II
150mm Railgun II
[Empty High slot]
150mm Railgun II
150mm Railgun II
150mm Railgun II

Small Ancillary Current Router I
Small Hybrid Burst Aerator I
Small Ionic Field Projector I



Tracking Speed Script x1
Nanite Repair Paste x20
Scan Resolution Script x1
```

**Comment by SpeedProg** [comment]
Reappeared for me too
Fit I have problem with is this:
```
[Vindicator, VeniVindiVG]
Damage Control II
Drone Damage Amplifier II
Drone Damage Amplifier II
Federation Navy Magnetic Field Stabilizer
Federation Navy Magnetic Field Stabilizer
Federation Navy Magnetic Field Stabilizer
Federation Navy Magnetic Field Stabilizer

Pithum C-Type Adaptive Invulnerability Field
True Sansha Stasis Webifier
Pithum C-Type Adaptive Invulnerability Field
Core C-Type 500MN Microwarpdrive
Federation Navy Stasis Webifier

Neutron Blaster Cannon II
Neutron Blaster Cannon II
Neutron Blaster Cannon II
Neutron Blaster Cannon II
Neutron Blaster Cannon II
Neutron Blaster Cannon II
Neutron Blaster Cannon II
Neutron Blaster Cannon II

Large Hybrid Burst Aerator II
[Empty Rig slot]
Large Anti-EM Screen Reinforcer I


Ogre II x5

Null L x10464
Void L x10792
```

**Comment by blitzmann** [comment]
here's the error:

```
Traceback (most recent call last):
  File "C:\Users\Ryan\Copy\Git\blitzmann\Pyfa\gui\mainFrame.py", line 667, in importFromClipboard
    fits = sFit.importFitFromBuffer(fromClipboard(), self.getActiveFit())
  File "C:\Users\Ryan\Copy\Git\blitzmann\Pyfa\service\fit.py", line 914, in importFitFromBuffer
    _, fits = Port.importAuto(bufferStr, activeFit=activeFit)
  File "C:\Users\Ryan\Copy\Git\blitzmann\Pyfa\service\port.py", line 122, in importAuto
    return "EFT", (cls.importEft(string),)
  File "C:\Users\Ryan\Copy\Git\blitzmann\Pyfa\service\port.py", line 273, in importEft
    if item.category.name == "Drone":
AttributeError: 'NoneType' object has no attribute 'category'
```

This happens with any kind of `[Empty * Slot]`.

To fix another bug, I changed the way some items might be returned from the database if they do not exist. I did not thing to check how it's handling in the import/export code.

For now I will revert part of my changes.
