### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by rafisv** [DarkFenX/Pyfa#500]
Name: python
Version: 2.7.10-56.1
Arch: x86_64

Metadata-Version: 2.0
Name: requests
Version: 2.9.1

On run:
Traceback (most recent call last):
  File "./pyfa.py", line 116, in <module>
    import service.prefetch
  File "/home/rafis/Desktop/pyfa/service/__init__.py", line 16, in <module>
    from service.pycrest import EVE
  File "/home/rafis/Desktop/pyfa/service/pycrest/__init__.py", line 13, in <module>
    from .eve import EVE
  File "/home/rafis/Desktop/pyfa/service/pycrest/eve.py", line 6, in <module>
    import requests
ImportError: No module named requests

**Comment by blitzmann** [comment]
You must install the `requests` python package as stated in the readme. This is a relatively new dependancy. If youre using the pyfa package from the Arch AUR, contact the maintaiAUR to getthe dependancies updates. Reopen issue and comment if you run into problems
